export enum ThresholdName {
    amcThreshold = "amcThreshold",
    caThreshold = "caThreshold",
    camThreshold = "camThreshold",
    cbmThreshold = "cbmThreshold",
    cboThreshold = "cboThreshold",
    ccThreshold = "ccThreshold",
    ceThreshold = "ceThreshold",
    damThreshold = "damThreshold",
    ditThreshold = "ditThreshold",
    icThreshold = "icThreshold",
    lcomThreshold = "lcomThreshold",
    lcom3Threshold = "lcom3Threshold",
    locThreshold = "locThreshold",
    mfaThreshold = "mfaThreshold",
    moaThreshold = "moaThreshold",
    nocThreshold = "nocThreshold",
    npmThreshold = "npmThreshold",
    rfcThreshold = "rfcThreshold",
    wmcThreshold = "wmcThreshold"
}